---
title: "Project"
output: html_document
---

```{r libraries, include=FALSE}
library(tidyverse)
library(phyloseq)
library(ggpicrust2)
library(GGally)
library('pheatmap')
```

## Load physloseq and rarefaction

```{r load_data}
meta = readRDS("ps.rds") %>%
  .@sam_data %>% data.frame() %>%
  rownames_to_column("sample_name")

ko = read.delim("pred_metagenome_unstrat.tsv", row.names=1)

```

# Differential Analysis

```{r}
#Healthy (control) in male and female

HC_difference = meta %>%
  filter(Group == "Healthy control (HC)")

ko_filt_HC = ko %>% select(all_of(HC_difference$sample_name))

daa_results_df_HC = pathway_daa(abundance = ko_filt_HC,
                             metadata = HC_difference,
                             group = "Gender",
                             daa_method = "LinDA",
                             select = NULL, reference = NULL)

daa_annotated_results_df_HC = pathway_annotation(pathway = "KO",
                                              daa_results_df = daa_results_df_HC,
                                              ko_to_kegg = TRUE)

saveRDS(daa_annotated_results_df_HC, "daa_annotated_results_df_HC.rds")
daa_annotated_results_df_HC = read_rds("daa_annotated_results_df_HC.rds")


#Chronic Gastiritis (CG) in male and Female
CG_difference = meta %>%
  filter(Group == "Chronic gastritis (CG)")
ko_filt_CG= ko %>% select(all_of(CG_difference$sample_name))

daa_results_df_CG = pathway_daa(abundance = ko_filt_CG,
                             metadata = CG_difference,
                             group = "Gender",
                             daa_method = "LinDA",
                             select = NULL, reference = NULL)

daa_annotated_results_df_CG = pathway_annotation(pathway = "KO",
                                              daa_results_df = daa_results_df_CG,
                                              ko_to_kegg = TRUE)

saveRDS(daa_annotated_results_df_CG, "daa_annotated_results_df_CG.rds")
daa_annotated_results_df_CG = read_rds("daa_annotated_results_df_CG.rds")

#Intestinal Metaplasia (IM) in male and Female
IM_difference = meta %>%
  filter(Group == "Intestinal metaplasia (IM）")
ko_filt_IM= ko %>% select(all_of(IM_difference$sample_name))

daa_results_df_IM = pathway_daa(abundance = ko_filt_IM,
                             metadata = IM_difference,
                             group = "Gender",
                             daa_method = "LinDA",
                             select = NULL, reference = NULL)

daa_annotated_results_df_IM = pathway_annotation(pathway = "KO",
                                              daa_results_df = daa_results_df_IM,
                                              ko_to_kegg = TRUE)

saveRDS(daa_annotated_results_df_IM, "daa_annotated_results_df_IM.rds")
daa_annotated_results_df_IM = read_rds("daa_annotated_results_df_IM.rds")

#Intraepithelial neoplasia (IN) in male and Female
IN_difference = meta %>%
  filter(Group == "Intraepithelial neoplasia (IN)")
ko_filt_IN= ko %>% select(all_of(IN_difference$sample_name))

daa_results_df_IN = pathway_daa(abundance = ko_filt_IN,
                             metadata = IN_difference,
                             group = "Gender",
                             daa_method = "LinDA",
                             select = NULL, reference = NULL)

daa_annotated_results_df_IN = pathway_annotation(pathway = "KO",
                                              daa_results_df = daa_results_df_IN,
                                              ko_to_kegg = TRUE)

saveRDS(daa_annotated_results_df_IN, "daa_annotated_results_df_IN.rds")
daa_annotated_results_df_IN = read_rds("daa_annotated_results_df_IN.rds")

#"Gastric cancer (GC) in male and Female
GC_difference = meta %>%
  filter(Group == "Gastric cancer (GC)")
ko_filt_GC= ko %>% select(all_of(GC_difference$sample_name))

daa_results_df_GC = pathway_daa(abundance = ko_filt_GC,
                             metadata = GC_difference,
                             group = "Gender",
                             daa_method = "LinDA",
                             select = NULL, reference = NULL)

daa_annotated_results_df_GC = pathway_annotation(pathway = "KO",
                                              daa_results_df = daa_results_df_GC,
                                              ko_to_kegg = TRUE)

saveRDS(daa_annotated_results_df_GC, "daa_annotated_results_df_GC.rds")
daa_annotated_results_df_GC = read_rds("daa_annotated_results_df_GC.rds")

```

# Functional Analysis Graphs

```{r}
source("ggpicrust2_errorbar_function_fixed.R")

# HC graph - no significance
daa_annotated_results_df_HC_sig = daa_annotated_results_df_HC %>% 
    drop_na() %>%
  filter( p_adjust<4 & abs(log2_fold_change >= 1))

nrow(daa_annotated_results_df_HC_sig)
summary(daa_annotated_results_df_HC)

# HC_graph = pathway_errorbar_fixed(abundance = ko_filt_HC,
 #                                 daa_results_df = daa_annotated_results_df_HC_sig,
  #                                Group = HC_difference$Gender,
     #                             p_values_threshold = 0.7,
   #                               wrap_label = T, wraplength = 50,
     #                             order_by_log = F,
        #                          order = "pathway_class",
       #                           ko_to_kegg = TRUE,
         #                         p_value_bar = TRUE,
       #                           x_lab = "pathway_name")


# CG graph
daa_annotated_results_df_CG_sig = daa_annotated_results_df_CG %>% 
  filter( p_adjust<=0.05 & abs(log2_fold_change >= 2.15))

nrow(daa_annotated_results_df_CG_sig)

CG_graph = pathway_errorbar_fixed(abundance = ko_filt_CG,
                                  daa_results_df = daa_annotated_results_df_CG_sig,
                                  Group = CG_difference$Gender,
                                  p_values_threshold = 0.05,
                                  wrap_label = T, wraplength = 250,
                                  order_by_log = F,
                                  order = "pathway_class",
                                  ko_to_kegg = TRUE,
                                  p_value_bar = TRUE,
                                  x_lab = "pathway_name")

CG_graph
ggsave("CG graph final.png", plot=CG_graph, width =20, height = 16)


# IM graph - no significance
daa_annotated_results_df_IM_sig = daa_annotated_results_df_IM %>% 
  filter( p_adjust<=0.1 & abs(log2_fold_change >= 1.25))


IM_graph = pathway_errorbar_fixed(abundance = ko_filt_IM,
                                  daa_results_df = daa_annotated_results_df_IM_sig,
                                  Group = IM_difference$Gender,
                                  p_values_threshold = 0.05,
                                  wrap_label = T, wraplength = 50,
                                  order_by_log = F,
                                  order = "pathway_class",
                                  ko_to_kegg = TRUE,
                                  p_value_bar = TRUE,
                                  x_lab = "pathway_name")

IM_graph
ggsave("IM graph final.png", plot=IM_graph, width =20, height = 16)

# IN graph 
daa_annotated_results_df_IN_sig = daa_annotated_results_df_IN %>% 
  filter( p_adjust<=0.005 & abs(log2_fold_change >= 3.5))

daa_annotated_results_df_IN_sig2 = daa_annotated_results_df_IN %>% 
  filter( p_adjust<=0.05 & abs(log2_fold_change >= 2.15))

view(daa_annotated_results_df_IN_sig2)

IN_graph = pathway_errorbar_fixed(abundance = ko_filt_IN,
                                  daa_results_df = daa_annotated_results_df_IN_sig,
                                  Group = IN_difference$Gender,
                                  p_values_threshold = 0.005,
                                  wrap_label = T, wraplength = 200,
                                  order_by_log = F,
                                  order = "pathway_class",
                                  ko_to_kegg = TRUE,
                                  p_value_bar = TRUE,
                                  x_lab = "pathway_name")


IN_graph
ggsave("IN graph final.png", plot=IN_graph, width =22, height = 14)

# GC graph - no significant difference
daa_annotated_results_df_GC_sig = daa_annotated_results_df_GC %>% 
  filter( p_adjust<=0.05 & abs(log2_fold_change >= 1))

nrow(daa_annotated_results_df_GC_sig)


GC_graph = pathway_errorbar_fixed(abundance = ko_filt_GC,
                                  daa_results_df = daa_annotated_results_df_GC_sig,
                                  Group = GC_difference$Gender,
                                  p_values_threshold = 0.005,
                                  wrap_label = T, wraplength = 200,
                                  order_by_log = F,
                                  order = "pathway_class",
                                  ko_to_kegg = TRUE,
                                  p_value_bar = TRUE,
                                  x_lab = "pathway_name")

GC_graph
ggsave("GC graph final.png", plot=GC_graph, width =20, height = 16)



```

# Heat map and PCA
```{r}
# CG
ko_relab = read.delim("pred_metagenome_unstrat.tsv", row.names=1) %>% 
  apply(2,function(x) x/sum(x)) %>% as.data.frame()
colSums(ko_relab)

color_palette <- colorRampPalette(c("blue", "white", "red"))(40)
breaks <- seq(-1, 1, length.out = 41)

sig_features_CG = daa_annotated_results_df_CG_sig %>% 
  pull('feature') %>% unique()

stats_CG = ko_relab %>% t() %>%  
  as.data.frame() %>% 
  select(all_of(sig_features_CG)) %>% 
  cor(method = 'spearman') 

pheatmap(stats_CG, 
         clustering_distance_rows = "euclidean",  
         clustering_distance_cols = "euclidean", 
         clustering_method = "complete",          
         color = color_palette, 
         breaks = breaks,
         main = '',
         fontsize_row = 10, 
         fontsize_col = 10,
         filename = "CG Heatmap.png",
         height= 9, width = 9)

CG_PCA = pathway_pca(abundance = ko_filt_CG,
            metadata = CG_difference, 
            group = "Gender")

ggsave("CG PCA plot.png", plot=CG_PCA, width =12, height = 8)

# IN
sig_features_IN = daa_annotated_results_df_IN_sig %>% 
  pull('feature') %>% unique()

stats_IN = ko_relab %>% t() %>%  
  as.data.frame() %>% 
  select(all_of(sig_features_IN)) %>% 
  cor(method = 'spearman') 


pheatmap(stats_IN, 
         clustering_distance_rows = "euclidean",  
         clustering_distance_cols = "euclidean", 
         clustering_method = "complete",          
         color = color_palette, 
         breaks = breaks,
         main = '',
         fontsize_row = 10, 
         fontsize_col = 10,
         filename = "IN Heatmap.png",
         height= 9, width = 9)

IN_PCA = pathway_pca(abundance = ko_filt_IN,
            metadata = IN_difference, 
            group = "Gender")

ggsave("IN PCA plot.png", plot=IN_PCA, width =12, height = 8)

# HC
HC_PCA = pathway_pca(abundance = ko_filt_HC,
            metadata = HC_difference, 
            group = "Gender")

ggsave("HC PCA plot.png", plot=HC_PCA, width =12, height = 8)

# IM
IM_PCA = pathway_pca(abundance = ko_filt_IM,
            metadata = IM_difference, 
            group = "Gender")

ggsave("IM PCA plot.png", plot=IM_PCA, width =12, height = 8)

# GC
GC_PCA = pathway_pca(abundance = ko_filt_GC,
            metadata = GC_difference, 
            group = "Gender")

ggsave("GC PCA plot.png", plot=GC_PCA, width =12, height = 8)


```


# Additional inquiries
```{r}

# CG
CG_plot = daa_annotated_results_df_CG_sig %>%
  ggplot(aes(x=log2_fold_change,
             y=pathway_name,
             size=p_adjust)) +
  geom_point() +
  labs(x= "Log2 Fold Change",
       y= "Pathway",
       size= "Adjusted p-value",
       title= "CG Differential Pathways") +
  theme_bw()

CG_plot
ggsave("CG supplement plot.png", plot=CG_plot, width =12, height = 8)

# IN
IN_plot = daa_annotated_results_df_IN_sig %>%
  ggplot(aes(x=log2_fold_change,
             y=pathway_name,
             size=p_adjust)) +
  geom_point() +
  labs(x= "Log2 Fold Change",
       y= "Pathway",
       size= "Adjusted p-value",
       title= "IN Differential Pathways") +
  theme_bw()

IN_plot
ggsave("IN supplement plot.png", plot=IN_plot, width =12, height = 8)



```


